apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-automatic-workflow-config
  namespace: dev
  labels:
    app.kubernetes.io/name: aks-automatic-workflow
    kubernetes.azure.com/generator: devhub
data: